import pandas as pd
statne = pd.read_excel('/workspaces/D2I-Jupyter-Notebook-Tools/Vanessa_Trial/Statistical Neighbours.xlsx', sheet_name='Stats Neighbours')
print(statne)
region = pd.read_excel('/workspaces/D2I-Jupyter-Notebook-Tools/Vanessa_Trial/Statistical Neighbours.xlsx', sheet_name='Regions and MCA')
print(region)
# The files above only changes once Stats Neighbours updated
ofsted = pd.read_excel('/workspaces/D2I-Jupyter-Notebook-Tools/Vanessa_Trial/ofsted_csc_send_overview.xlsx' ,usecols=['la_code','outcome_grade','previous_inspection_date'],engine='openpyxl')
print(ofsted) #update ofsted file every quarter - needs to be downloaded from SEND OFSTED Inspections Scrapes (Rob)
region.info()
ofsted.info()
print(region.dtypes)
print (ofsted.dtypes)
region_merged=region.merge(ofsted,left_on='LA Code', right_on='la_code',how='left')
print(region_merged)
region_merged_cut=region_merged.drop(columns=['la_code','previous_inspection_date'])
print(region_merged_cut)
population = pd.read_excel('/workspaces/D2I-Jupyter-Notebook-Tools/Vanessa_Trial/ONS Mid Year 2024 - corrected names.xlsx',sheet_name='CreateCustomGroup',skiprows=4)
population.info()
population=population.drop(population.columns[[0,2,3,4]],axis=1)
print(population.dtypes)
print(population)